.PHONY: all
all:
	pdflatex mathiabo_oyvinrob_p3.tex
	bibtex mathiabo_oyvinrob_p3
	pdflatex mathiabo_oyvinrob_p3.tex
	pdflatex mathiabo_oyvinrob_p3.tex

.PHONY: clean
clean:
	rm -f *.aux *.bbl *.blg *.xml *.log *blx.bib *blg *blg
